image: node:12

stages:
    - check
    - package


check:
    stage: check
    script:
        - npm ci && npm run lint

package:
    stage: package
    rules:
        -
            when: manual
    artifacts:
        paths:
            - dist/*.tar.gz
    script:
        - npm ci && npm run package:prod