default:
    image: node:12-buster
    cache:
        key:
            files:
                - package.json
        paths:
            - node_modules

stages:
    - check
    - package

check:
    stage: check
    cache:
        policy: push
    artifacts:
        paths:
            - dist/
    script:
        - apt-get update && apt-get install -y jq
        - make clean dist check

package-web:
    stage: package
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    cache:
        policy: pull
    artifacts:
        expire_in: never
        paths:
            - target/*
    script:
        - apt-get update && apt-get install -y jq
        - make package-web

package-electron-linux:
    image: electronuserland/builder:12
    stage: package
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    cache:
        policy: pull
    artifacts:
        expire_in: never
        paths:
            - target/*
    script:
        - apt-get update && apt-get install -y jq fakeroot dpkg
        - make package-electron-linux

package-electron-windows:
    stage: package
    image: electronuserland/builder:wine-mono
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    cache:
        policy: pull
    artifacts:
        expire_in: never
        paths:
            - target/*
    script:
        # deps
        - apt-get update && apt-get install -y jq
        # Fix image's bundled 32bit wine folder
        - rm -rf /root/.wine
        - winecfg
        # make package
        - make package-electron-windows

docker:
    stage: package
    services:
        - docker:19.03-dind
    image: docker:19.03
    cache:
        policy: pull
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    script:
        - apk add make jq
        - echo -n $DOCKER_PASSWORD | docker login -u tonyfinn --password-stdin https://index.docker.io/v1/
        - make docker && make publish-docker
