default:
    image: node:12
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules/
            - dist/

stages:
    - check
    - package
    - publish

check:
    stage: check
    script:
        - make clean
        - make check

package-web:
    stage: package
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    script:
        - wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O jq
        - chmod +x jq
        - make package-web

package-electron-linux:
    stage: package
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    script:
        - apt-get update && apt-get install -y rpm jq fakeroot
        - make package-electron-linux

package-electron-windows:
    stage: package
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    script:
        - apt-get update && apt-get install -y wine mono jq
        - make package-electron-windows

archive:
    stage: publish
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    artifacts:
        expire_in: never
        paths:
            - target/*
    script:
        - echo "Placeholder to collect artifacts in one place"

docker:
    stage: publish
    services:
        - docker:19.03-dind
    image: docker:19.03
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    script:
        - apk add jq make
        - echo -n $DOCKER_PASSWORD | docker login -u tonyfinn --password-stdin https://index.docker.io/v1/
        - make docker && make publish-docker
