image: node:12

stages:
    - check
    - package

check:
    stage: check
    script:
        - make check

package:
    stage: package
    rules:
        - if: $CI_COMMIT_TAG
          when: on_success
    artifacts:
        paths:
            - dist/*.tar.gz
    script:
        - make package
