FROM node:12-buster
# jq is used by build scripts, rest used by cypress
RUN apt-get update && apt-get install -y jq libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
